Repository vmeretail/subscriptionservice, pull requests merged in 2019-12, with the labels that each got.

#1 Initial Codebase
  README.md
  SubscriptionService.sln
  src/SubscriptionService/Configuration/Subscription.cs
  src/SubscriptionService/ISubscriptionService.cs
  src/SubscriptionService/SubscriptionService.cs
  src/SubscriptionService/SubscriptionService.csproj
  test/SubscriptionService.UnitTests/SubscriptionService.UnitTests.csproj
  test/SubscriptionService.UnitTests/SubscriptionServiceTests.cs
  test/SubscriptionService.UnitTests/TestData.cs
  test/TestHarness/Program.cs
  test/TestHarness/TestHarness.csproj
Labels: enhancement

#4 Add CI workflows
  .github/releasedrafter
  .github/workflows/createrelease.yml
  .github/workflows/pullrequest.yml
  .github/workflows/releasemanagment
Labels: workflows

#5 Rename releasedrafter to release-drafter
  .github/release-drafter
Labels: workflows

#6 Rename release-drafter to release-drafter.yml
  .github/release-drafter.yml
Labels: workflows

#7 Rename releasemanagment to releasemanagment.yml
  .github/workflows/releasemanagment.yml
Labels: workflows

#26 UnitTests project removed from code analysis, and a unit test added i…
  test/SubscriptionService.UnitTests/SubscriptionService.UnitTests.csproj
  test/SubscriptionService.UnitTests/SubscriptionTests.cs
Labels: enhancement

#28 Accept both String and Uri for endpoint address
  src/SubscriptionService/Configuration/Subscription.cs
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.UnitTests/SubscriptionTests.cs
  test/SubscriptionService.UnitTests/TestData.cs
  test/TestHarness/Program.cs
Labels: enhancement

#30 Added Guards on Subscription Service Class ctor
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.UnitTests/SubscriptionServiceTests.cs
  test/SubscriptionService.UnitTests/TestData.cs
Labels: bug

#34 Update createrelease.yml
  .github/workflows/createrelease.yml
Labels: workflows

#36 Introduction of internal Subscription object for holding configuration passed in from caller.
  src/SubscriptionService/Domain/Subscription.cs
  src/SubscriptionService/Factories/SubscriptionFactory.cs
  src/SubscriptionService/SubscriptionService.cs
  src/SubscriptionService/SubscriptionService.csproj
  test/SubscriptionService.UnitTests/SubscriptionFactoryTests.cs
  test/SubscriptionService.UnitTests/SubscriptionTests.cs
Labels: enhancement

#37 System events now ignored.
  src/SubscriptionService/SubscriptionService.cs
Labels: enhancement

#39 HttpClient now being used per subscription.
  src/SubscriptionService/SubscriptionService.cs
Labels: enhancement
