Repository vmeretail/subscriptionservice, pull requests merged in 2020-03, with the labels that each got.

#86 Remove Subscription Support Added
  src/SubscriptionService/ISubscriptionService.cs
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.UnitTests/SubscriptionServiceTests.cs
  test/TestHarness/Program.cs
Labels: feature

#87 Logger injected into service
  examples/ConsoleApplication/ConsoleApplication/Program.cs
  examples/Core3WorkerServiceExample/Core3WorkerServiceExample.csproj
  examples/Core3WorkerServiceExample/Worker.cs
  src/SubscriptionService/ISubscriptionService.cs
  src/SubscriptionService/SubscriptionService.cs
  src/SubscriptionService/SubscriptionService.csproj
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/SubscriptionService.IntegrationTests.csproj
  test/SubscriptionService.UnitTests/SubscriptionService.UnitTests.csproj
  test/TestHarness/Program.cs
Labels: feature

#88 Added event debugging projection
  test/SubscriptionService.IntegrationTests/Helper/DockerHelper.cs
Labels: enhancement

#90 Logged out serialised event for NAK'd events.
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
Labels: enhancement

#91 Introduced SubscriptionServiceBuilder to assist when creating Subscri…
  examples/ConsoleApplication/ConsoleApplication/Program.cs
  examples/Core3WorkerServiceExample/Program.cs
  examples/Core3WorkerServiceExample/Worker.cs
  examples/Core3WorkerServiceExample/WorkerEventFactory.cs
  src/SubscriptionService/SubscriptionService.cs
  src/SubscriptionService/SubscriptionServiceBuilder.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.UnitTests/SubscriptionServiceBuilderTests.cs
  test/SubscriptionService.UnitTests/SubscriptionServiceTests.cs
  test/SubscriptionService.UnitTests/TestEventFactory.cs
  test/TestHarness/Program.cs
Labels: enhancement

#110 Added in check when Event Store config not found
  test/SubscriptionService.IntegrationTests/Helper/DockerHelper.cs
Labels: bug

#113 Sensitive data removed
  .github/workflows/pullrequest.yml
  test/SubscriptionService.IntegrationTests/appsettings.json
  test/TestHarness/Program.cs
Labels: bug

#114 NLog Trace now written in CI
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
  test/SubscriptionService.IntegrationTests/nlog.config
Labels: bug

#115 Tests added for Stop method
  src/SubscriptionService/Subscription.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
  test/TestHarness/Program.cs
Labels: feature

#118 Testing/catchupintegration
  .github/release-drafter.yml
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
Labels: maintenance, testing

#119 Trace reviewed and logging fixed in tests
  src/SubscriptionService/Subscription.cs
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
Labels: maintenance

#121 Add Latest Checkpoint Handler
  examples/ConsoleApplication/ConsoleApplication/CatchupSubscriptions/DrainEventsOnSubscriptionDroppedExamples.cs
  examples/ConsoleApplication/ConsoleApplication/CatchupSubscriptions/EventAppearedHandler.cs
  examples/ConsoleApplication/ConsoleApplication/CatchupSubscriptions/LastCheckpoint.cs
  examples/ConsoleApplication/ConsoleApplication/Program.cs
  src/SubscriptionService/Builders/CatchupSubscriptionBuilder.cs
  src/SubscriptionService/Builders/SubscriptionBuilder.cs
  src/SubscriptionService/Subscription.cs
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
  test/TestHarness/Program.cs
Labels: enhancement

#123 Add Latest Checkpoint Handler
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/TestHarness/Program.cs
Labels: enhancement

#124 Fix the worker service example after refactor
  examples/Core3WorkerServiceExample/Worker.cs
  src/SubscriptionService/Subscription.cs
Labels: examples, maintenance

#125 Reformatted theory test name
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
Labels: bug

#130 Update console application comments
  examples/ConsoleApplication/ConsoleApplication/CatchupSubscriptions/DrainEventsOnSubscriptionDroppedExamples.cs
  examples/ConsoleApplication/ConsoleApplication/CatchupSubscriptions/LastCheckpoint.cs
  examples/ConsoleApplication/ConsoleApplication/PersistentSubscriptions/OverrideHandlers.cs
  examples/ConsoleApplication/ConsoleApplication/Program.cs
Labels: documentation

#133 Add supported ES versions to readme
  README.md
Labels: documentation

#132 Added ability to pass in action to handle dead letter processing
  src/SubscriptionService/Builders/CatchupSubscriptionBuilder.cs
  src/SubscriptionService/Subscription.cs
  test/SubscriptionService.IntegrationTests/CatchupSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/appsettings.json
  test/SubscriptionService.UnitTests/CatchupSubscriptionBuilderTests.cs
  test/TestHarness/Program.cs
Labels: enhancement
