Repository vmeretail/subscriptionservice, pull requests merged in 2020-01, with the labels that each got.

#43 Initial End To End Test
  .github/workflows/createrelease.yml
  .github/workflows/pullrequest.yml
  SubscriptionService.sln
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/DockerHelper.cs
  test/SubscriptionService.IntegrationTests/Dockerfile
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/Retry.cs
  test/SubscriptionService.IntegrationTests/SubscriptionService.IntegrationTests.csproj
  test/SubscriptionService.IntegrationTests/db.json
Labels: enhancement

#49 Error Handler added into Service, along with multiple event testing.
  src/SubscriptionService/ISubscriptionService.cs
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
  test/TestHarness/Program.cs
Labels: enhancement

#52 New Subscription Configuration Fields
  src/SubscriptionService/Configuration/Subscription.cs
  src/SubscriptionService/Domain/Subscription.cs
  src/SubscriptionService/Factories/SubscriptionFactory.cs
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.UnitTests/SubscriptionFactoryTests.cs
  test/SubscriptionService.UnitTests/SubscriptionTests.cs
  test/SubscriptionService.UnitTests/TestData.cs
  test/TestHarness/Program.cs
Labels: enhancement

#53 Minor workflow updates
  .github/workflows/createrelease.yml
  .github/workflows/pullrequest.yml
Labels: workflows

#54 Bug/missing image
  src/SubscriptionService/SubscriptionService.csproj
  src/SubscriptionService/vme.png
Labels: bug

#58 Added number of downloads badge to readme
  README.md
Labels: workflows

#60 Added console example code
  SubscriptionService.sln
  examples/ConsoleApplication/ConsoleApplication/ConsoleApplication.csproj
  examples/ConsoleApplication/ConsoleApplication/Program.cs
Labels: enhancement

#61 Added Worker Service example
  Core3WorkerServiceExample/Core3WorkerServiceExample.csproj
  Core3WorkerServiceExample/Program.cs
  Core3WorkerServiceExample/Properties/launchSettings.json
  Core3WorkerServiceExample/Worker.cs
  Core3WorkerServiceExample/appsettings.json
  SubscriptionService.sln
  examples/ConsoleApplication/ConsoleApplication/Program.cs
Labels: enhancement

#62 Move Worker Service example
  SubscriptionService.sln
  examples/Core3WorkerServiceExample/Core3WorkerServiceExample.csproj
  examples/Core3WorkerServiceExample/Program.cs
  examples/Core3WorkerServiceExample/Properties/launchSettings.json
  examples/Core3WorkerServiceExample/Worker.cs
  examples/Core3WorkerServiceExample/appsettings.json
Labels: enhancement

#63 Added further integration tests
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/db.json
Labels: workflows

#64 Update labels handled by Release Drafter
  .github/release-drafter.yml
Labels: workflows

#66 Ability to add new subscriptions to service after Start is called
  README.md
  examples/ConsoleApplication/ConsoleApplication/ConsoleApplication.csproj
  examples/ConsoleApplication/ConsoleApplication/Program.cs
  examples/Core3WorkerServiceExample/Core3WorkerServiceExample.csproj
  examples/Core3WorkerServiceExample/Worker.cs
  src/SubscriptionService/ISubscriptionService.cs
  src/SubscriptionService/SubscriptionService.cs
  test/SubscriptionService.IntegrationTests/DockerHelper.cs
  test/SubscriptionService.IntegrationTests/PersistentSubscriptionsTests.cs
  test/SubscriptionService.IntegrationTests/TestsFixture.cs
  test/SubscriptionService.UnitTests/SubscriptionServiceTests.cs
  test/TestHarness/Program.cs
Labels: feature

#67 Remove test code
  test/TestHarness/Program.cs
Labels: skip-changelog
